---
apiVersion: v1
kind: Service
metadata:
  name: productdetails-app
spec:
  selector:
    app: productdetails-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
    

...