---
- name: windows ping
  hosts: windows
  gather_facts: no
  tasks:
    - name: Ensure minikube is running
      win_shell: minikube status 
      register: minikube_status
    
    - name: start minikube
      win_shell: minikube start --driver=virtualbox --no-vtx-check
      when: minikube_status.rc !=0
      
      
...



