---
- name: windows ping
  hosts: windows
  gather_facts: no
  vars:
    workdir: D:\work\kubernetes_practice\power_tiller_app\second-mf
  tasks:
    - name: Ensure minikube is running
      win_shell: minikube status 
      register: minikube_status
    
    # - name: start minikube
    #   win_shell: minikube start --driver=virtualbox --no-vtx-check
    #   when: minikube_status.rc !=0

    - name: deploy statefulset 
      win_shell: kubectl apply -f {{ workdir }}/mf-second-mysql_statefulset.yml

    - name: deploy application
      win_shell: kubectl apply -f {{ workdir }}/mf-second-Deployment.yml 
    
    - name: create service 
      win_shell: kubectl apply -f {{ workdir }}/mf-second-Service.yml

    - name: start minikube service 
      win_shell: minikube service mf-second-app
...
