---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productdetails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productdetails-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: productdetails-app
    spec:
      containers:
        - name: productdetails-app
          image: samadhangapat/productdetailsms:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://second-mysql:3306/mfsecond
            - name: SPRING_DATASOURCE_USERNAME
              value: root 
            - name: SPRING_DATASOURCE_PASSWORD
              value: root

      restartPolicy: Always

...